### ISSUE TITLE
Unable to load the voice model 

### ISSUE THREAD

**Issue by ub1979** [SayanoAI/RVC-Studio#23]
Hi I Tried to put model in RAV folder and index in RAV /.index / directory 
but its not showing any model. I even downloaded using the home interface to download the models but still it's not showing/loading any voice model . 
will be grateful if someone guide me . 
Thanks

**Comment by SayanoAI** [comment]
You should put your models in the RVC directory and then start the RVC server. After you navigate to the inference page, refresh your data and your model should appear in the dropdown.

**Comment by ub1979** [comment]
I did everything as you said ( I guess but its not working ) may be I am missing something 
<img width="819" alt="Screenshot 2024-01-08 at 04 25 57" src="https://github.com/SayanoAI/RVC-Studio/assets/34165536/ffa7d6e5-18e8-42e2-bd6f-1ee5973277e3">
<img width="1512" alt="Screenshot 2024-01-08 at 04 25 16" src="https://github.com/SayanoAI/RVC-Studio/assets/34165536/12fa254d-38a9-416d-b0bb-606f7670dfdb">
<img width="1036" alt="Screenshot 2024-01-08 at 04 24 54" src="https://github.com/SayanoAI/RVC-Studio/assets/34165536/b2b4b635-6aed-4fa9-856a-ff50ba8eeefc">
<img width="834" alt="Screenshot 2024-01-08 at 04 24 15" src="https://github.com/SayanoAI/RVC-Studio/assets/34165536/f2a92476-bad9-4865-92de-239f00e2745d">
<img width="824" alt="Screenshot 2024-01-08 at 04 23 37" src="https://github.com/SayanoAI/RVC-Studio/assets/34165536/e472c41d-d756-48db-a533-9a3bbfc2991f">

**Comment by SayanoAI** [comment]
try pulling the latest patch. If your RVC server is working then navigating to "http://localhost:5555/" should show you a page with text like this: {"status":"OK","rvc": ... }
