### ISSUE TITLE
[BUG] Inference tab -> Scan models doesn't work

### ISSUE THREAD

**Issue by AlexeyArtemev** [SayanoAI/RVC-Studio#24]
**Description**
The button for models scan(`Refresh data` in Inference tab) doesn't do anything.
![image](https://github.com/SayanoAI/RVC-Studio/assets/53113374/a75667e7-9f8d-4d68-8cda-c4bd1550dd2f)

The scan doesn't work with or without the RVC server. The RVC server, however, can see the model right after the start:
```{"status":"OK","rvc":["repetur"],"uvr":[],"denoise":[]} # output at http://localhost:5555/, where repetur is model name```

The model and index are inside `models/RVC` folder(index is in `models/RVC/.index`), the model was trained with RVC-Studio.

No errors are being thrown in the console after pushing the button. The only errors i've encountered during my user journey from Home tab to training and up to infer are:
```
Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?
Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?
Invalid URL 'None/preprocess': No scheme supplied. Perhaps you meant https://None/preprocess?
Invalid URL 'None/postprocess': No scheme supplied. Perhaps you meant https://None/postprocess?
'<' not supported between instances of 'NoneType' and 'int'
'<' not supported between instances of 'NoneType' and 'int'
'<' not supported between instances of 'NoneType' and 'int'
```

but as far as i can tell they do not interfere with anything and the model training(which is the only thing i've done so far besides downloading hubert, ffmpeg, etc.) went fine.

**Comment by AlexeyArtemev** [comment]
it turns out you need not only turn on the RVC server, but the button won't work from the first time you open inference tab. After viewing every other tab and going back to inference the button worked. Can't say if it's some kind of delay or other issue

**Comment by SayanoAI** [comment]
yeah, that's caused by the LRU caching I used for the API. I might disable that for localhost
