### ISSUE TITLE
mono instead of stereo

### ISSUE THREAD

**Issue by Neovolter** [SayanoAI/RVC-Studio#26]
how can I output a stereo audio file instead of mono?

**Comment by SayanoAI** [comment]
The original RVC model only works on mono audio afaik. You can try duplicating the channel before exporting.

**Comment by SayanoAI** [comment]
stereo export has been implemented in latest commit: https://github.com/SayanoAI/RVC-Studio/commit/9a954f5db2cc91527b4216ebdd65ba622b3075e7
