### ISSUE TITLE
Train- Process data errors

### ISSUE THREAD

**Issue by brcisna** [SayanoAI/RVC-Studio#28]
Installed RVC-Studio on two Debian 12 linux machines
1 x Python 3.8.9 , 1 x 3.10.12 
*NO* GPU only CPU,,,,,for completeness

ffmpeg-python IS installed 

Training Process data, i get the following errors, have the audio files (wav) inside a folder zipped.
'copy path' from file browser into the ' Enter the path of the training folder:' with trailing forward slash (Linux) 
-------------------------------------------------------------------
*EDIT*:

Set up stderr output and this is what the stderr throws
RVC-Studio/input/inoutfiles.zip: Invalid data found when processing input

I have three wav files placed inside a folder in zip format that is inside the input directory path given in the datapath line ,,default shows 'dataset' 
The native version of ffmpeg-5.1.4-0 on both Linux machines
------------------------------------------------------------------------

`VC-Studio/preprocessing_utils.py", line 73, in pipeline
    audio = load_audio(path, self.sr)
  File "/home/brcisna/MyPrograms/rvcstudio/RVC-Studio/lib/audio.py", line 43, in load_audio
    raise RuntimeError(f"Failed to load audio: {e}")
RuntimeError: Failed to load audio: ffmpeg error (see stderr output for detail)

/home/brcisna/MyPrograms/rvcstudio/RVC-Studio/datasets/elvis.zip->Traceback (most recent call last):
  File "/home/brcisna/MyPrograms/rvcstudio/RVC-Studio/lib/audio.py", line 38, in load_audio
    ffmpeg.input(file, threads=0)
  File "/home/brcisna/.pyenv/versions/3.10.12/envs/RVC-Studio/lib/python3.10/site-packages/ffmpeg/_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/brcisna/MyPrograms/rvcstudio/RVC-Studio/preprocessing_utils.py", line 73, in pipeline
    audio = load_audio(path, self.sr)
  File "/home/brcisna/MyPrograms/rvcstudio/RVC-Studio/lib/audio.py", line 43, in load_audio
    raise RuntimeError(f"Failed to load audio: {e}")
RuntimeError: Failed to load audio: ffmpeg error (see stderr output for detail)

end preprocess`

**Comment by SayanoAI** [comment]
Can you try extracting the zip file into it's own folder and point the training path to: "RVC-Studio/input/inoutfiles"

Your files should be something like "RVC-Studio/input/inoutfiles/file1.wav"
