### ISSUE TITLE
*Resolved* Docker image builds but does not connect to 0.0.0.0

### ISSUE THREAD

**Issue by brcisna** [SayanoAI/RVC-Studio#29]
building the docker image goes succesfully
when launching with 'docker container run rvc-studio' the web page comes up with,, 'refuse to connect to 0.0.0.0'

may be missing something. not familiar with docker. 

*Resolved*
when running docker had to add '--net=host' to get internet connectivity. eg. 'docker run --net=host rvc-studo'

TIA

**Comment by SayanoAI** [comment]
Can you also try `docker compose up --build` ? If that doesn't work then I'll have to add that to the yaml file
