### ISSUE TITLE
Realtime Conversion Error

### ISSUE THREAD

**Issue by 404Bye** [SayanoAI/RVC-Studio#32]
I'm new to this so I'm not sure what's going on.
![Screenshot 2024-03-27 184548](https://github.com/SayanoAI/RVC-Studio/assets/165200222/012fc47d-94d6-4720-be30-b07e7e87aad8)
![Screenshot 2024-03-27 184652](https://github.com/SayanoAI/RVC-Studio/assets/165200222/d111c750-fbb7-40d4-895d-f2dd34978946)

**Comment by SayanoAI** [comment]
I think you need to download a c++ compiler before running install-conda.bat. Did you install conda properly? https://conda.io/projects/conda/en/latest/user-guide/install/index.html
