### ISSUE TITLE
Streamlit - "Error running app"

### ISSUE THREAD

**Issue by ButterSus** [SayanoAI/RVC-Studio#34]
**URL:** https://rvc-studio.streamlit.app/

**Browser / Version:** Edge 126.0.2592.68 (Official build) (64-bit)
**Operating System:** Windows 11
**Tested Another Browser:** No

**Description:** App (website) is not running
**Steps to Reproduce:** Go to the link

![image](https://github.com/SayanoAI/RVC-Studio/assets/90126102/c4161913-5133-48b1-a924-215f08b231f6)

> Oh no.
> Error running app. If this keeps happening, please [contact support](https://github.com/sayanoai/rvc-studio/issues/new).

There is a console screenshot just in case:

![image](https://github.com/SayanoAI/RVC-Studio/assets/90126102/2849411f-574d-4a54-858a-a152e5496de5)

P.S.
Also tried out on Arch Linux + Firefox

**Comment by SayanoAI** [comment]
unfortunately the streamlit site was shut down
