### ISSUE TITLE
HEUR: Trojan-Downloader.BAT.Bitser.gen detected in conda-installer.bat

### ISSUE THREAD

**Issue by currentsound** [SayanoAI/RVC-Studio#35]
Virus scanner detected Trojan. Can't tell if it's false positive or not.

ChatGPT says this:

Why the Script Might Be Flagged:
Downloading and Executing Files: The script downloads the Miniconda installer from the internet and executes it. This behavior is similar to that of many malicious scripts, especially Trojans, which download and execute other files.

Modification of System Path: The script modifies the system path and installs software, actions that are often flagged by heuristic scanners as potentially dangerous.

General Heuristic Detection: HEUR indicates that the detection is heuristic-based, meaning the antivirus is guessing based on behavior rather than known signatures. False positives are possible in such cases.

**Comment by SayanoAI** [comment]
Thanks for letting me know. I'll get people to install conda manually and have them run conda-start script instead.
