### ISSUE TITLE
Error running app RVCStudio at streamlit

### ISSUE THREAD

**Issue by NishenSamuel** [SayanoAI/RVC-Studio#36]
Error - "Oh no.
Error running app. If this keeps happening, please [contact support](https://github.com/sayanoai/rvc-studio/issues/new)."

The message above displays whenever I try to access the "https://rvc-studio.streamlit.app/" url.
![image](https://github.com/user-attachments/assets/0470f967-55e0-4aec-9fb7-9197102abc58)

**Comment by SayanoAI** [comment]
unfortunately they've decided to close it due to the youtube music downloader.
