### ISSUE TITLE
trying to get rvc local

### ISSUE THREAD

**Issue by Mizu1993** [SayanoAI/RVC-Studio#4]
Checking if conda is already installed...
.cache folder does not exist. Creating it now.
Downloading Miniconda installer...

BITSADMIN version 3.0
BITS administration utility.
(C) Copyright Microsoft Corp.

Transfer complete.
Installing Miniconda...
Checking if conda is in the user path...
Something went wrong. Please check the installation log or submit a ticket at: https://github.com/SayanoAI/RVC-Studio/issues

Why?

**Comment by SayanoAI** [comment]
what does the conda-installer.log file say at the end?

**Comment by chunkyjackson** [comment]
I fixed this by installing Microconda manually you need to click checkbox that says Add to PATH while installing. Then you have to edit the "conda-start.bat" on line 14 change "CALL conda activate" to "CALL conda.bat activate" for it to work. I was going to make a pull request but I haven't had time.

**Comment by Mizu1993** [comment]
Thank you chunkyjackson. That helped

**Comment by Mizu1993** [comment]
![oui](https://github.com/SayanoAI/RVC-Studio/assets/145325472/51aec8eb-4257-421f-8290-09117cabad06)
Actually more problems even

**Comment by Mizu1993** [comment]
Did try to change line14 as stated, but still error 
![rrrr](https://github.com/SayanoAI/RVC-Studio/assets/145325472/42568fc5-e9cb-41f2-bc67-9eca1b52aed3)

**Comment by SayanoAI** [comment]
do you have your environment activated? 

What happens if you typed the following in your terminal?
`conda activate RVC-Studio`
